### ISSUE TITLE
Whisky error during  [Initializing score calculation...] -  [ERROR] invalid mode: 'rU'

### ISSUE THREAD

**Issue by Elodie-Wells** [haddocking/whiscy#8]
Hello, 

I keep getting this error, but I've already checked every file (whiscy.py, whiscy_setup.py, whiscy_data.py etc.) and made changes of 'rU' to 'r' that fixed earlier errors during the whiscy_setup. Despite 'rU' not existing anywhere anymore in my files, I can't seem to get past this error. My system is macOS and am using Python version 3.11.5. 

INPUT (tutorial example):
% python whiscy.py 1ppe_E.sur 1ppe_E.conv 1ppe_E.phylseq 1ppe_E.out

OUTPUT:
whiscy [INFO] Parsing surface list...
whiscy [INFO] Loading conversion table...
whiscy [INFO] Converting...
whiscy [INFO] Initializing score calculation...
whiscy [ERROR] invalid mode: 'rU'

Many thanks!

**Comment by rvhonorato** [comment]
Thanks for raising this issue, could you please also share the input files?

**Comment by rvhonorato** [comment]
This was happening because whiscy was using a deprecated feature - I've updated it to run with python 3.11, see #17
